// <auto-generated />
using System;
using Crude.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Crude.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Crude.Core.Entities.EnergyAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("CurrentReading")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("MaxConsumptionThreshold")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Assets");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CurrentReading = 0.0,
                            LastUpdated = new DateTime(2025, 12, 23, 14, 11, 35, 69, DateTimeKind.Utc).AddTicks(9950),
                            MaxConsumptionThreshold = 1000.0,
                            Name = "Main Transformer",
                            Status = "Healthy"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CurrentReading = 0.0,
                            LastUpdated = new DateTime(2025, 12, 23, 14, 11, 35, 70, DateTimeKind.Utc).AddTicks(400),
                            MaxConsumptionThreshold = 150.0,
                            Name = "Cooling Pump 01",
                            Status = "Healthy"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CurrentReading = 0.0,
                            LastUpdated = new DateTime(2025, 12, 23, 14, 11, 35, 70, DateTimeKind.Utc).AddTicks(410),
                            MaxConsumptionThreshold = 600.0,
                            Name = "Heavy Drill Rig",
                            Status = "Healthy"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
